Revert "msm: kgsl: Add gpu_frequency tracepoint to power trace system"
Fixes `undefined reference to `__tracepoint_gpu_frequency'`. This reverts commit 1b6f6cfd40bd2df26f4c5b939b33dddb5c09ceee.